### PR TITLE
docs ready for ReadTheDocs

### PR DESCRIPTION
**Pull request by jgrewe**

### CODE REVIEW

**Comment by achilleas-k** [comment]
Builds and looks good, but I'm getting some warnings when building locally.
```
[31;01m/Users/achilleas/code/nix/docs/getting_started.rst:61: WARNING: toctree contains reference to nonexisting document 'example_guide'[39;49;00m
[31;01m/Users/achilleas/code/nix/docs/index.rst:115: WARNING: toctree contains reference to nonexisting document 'contact'[39;49;00m
[31;01m/Users/achilleas/code/nix/docs/getting_started.rst:47: WARNING: unknown document: example_guide[39;49;00m
/usr/local/lib/python3.7/site-packages/sphinx_rtd_theme/search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  {{ super() }}
[31;01mWARNING: html_static_path entry '/Users/achilleas/code/nix/docs/_static' does not exist[39;49;00m
```

Are you getting the same?  We should probably deal with them before merging since the docs don't get frequent attention.

**Comment by jgrewe** [comment]
thanks @achilleas-k, all files are now in the repo, warnings are fixed, one thing that I would like to have is to also include the doxygen api documentation... need to play around with this, maybe a second step

**Comment by achilleas-k** [comment]
Still missing `example_guide` and `conf.py` has `html_static_path = ['_static']` but there's no `_static` directory.

**Comment by jgrewe** [comment]
@achilleas-k please try again :)

**Comment by achilleas-k** [comment]
Perfect :D

**Pull request merged**
