### PR TITLE
[cmake] rename nix lib to nixio

### PR DESCRIPTION
**Pull request by gicmo**
Next step of the big rename (issue #595)

### CODE REVIEW

**Comment by jgrewe** [comment]
just wondered whether we also want to rename variables like ```nix_INCLUDES```  etc. ?

**Comment by achilleas-k** [comment]
Is renaming the variables necessary? I suppose there's a consistency argument **for** renaming them. How far would those changes go? Build scripts, etc?

**Comment by jgrewe** [comment]
I guess it is not necessary, my argument would be solely the consistency. The change should not affect anything else than the cmake file

**Comment by gicmo** [comment]
Renaming things sounds fine to me, but I would suggest we wait with it until all the functional changes are done (i.e. the lib rename, and the nix tool rename). So we separate the aesthetics from the semantics.

**Pull request merged**
